// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7kqp1c3Mgm0Ane3770XrDMCU0rCZUMBI',
    appId: '1:99159866518:web:75b64b1bef72148a4f56b7',
    messagingSenderId: '99159866518',
    projectId: 'appo-656ac',
    authDomain: 'appo-656ac.firebaseapp.com',
    storageBucket: 'appo-656ac.appspot.com',
    measurementId: 'G-QGHZ1BWHSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXjrqVi28SifGdkyv3-GzmiQrmwXQ2MLI',
    appId: '1:99159866518:android:a224037b43a9dde24f56b7',
    messagingSenderId: '99159866518',
    projectId: 'appo-656ac',
    storageBucket: 'appo-656ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbnyE_PdyCiZdUT9elcOHoyt_FffneL7E',
    appId: '1:99159866518:ios:d41617f342d2d6704f56b7',
    messagingSenderId: '99159866518',
    projectId: 'appo-656ac',
    storageBucket: 'appo-656ac.appspot.com',
    iosClientId: '99159866518-hk2tsj0v0tnd5ja29s4c6gtm4cej659n.apps.googleusercontent.com',
    iosBundleId: 'com.example.appo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbnyE_PdyCiZdUT9elcOHoyt_FffneL7E',
    appId: '1:99159866518:ios:d41617f342d2d6704f56b7',
    messagingSenderId: '99159866518',
    projectId: 'appo-656ac',
    storageBucket: 'appo-656ac.appspot.com',
    iosClientId: '99159866518-hk2tsj0v0tnd5ja29s4c6gtm4cej659n.apps.googleusercontent.com',
    iosBundleId: 'com.example.appo',
  );
}
